name: Continuous integration
on:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "17 5 * * 5"

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      CI: true
    strategy:
      matrix:
        rust:
          - stable
          - beta

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        name: Setup toolchain
        with:
          toolchain: ${{ matrix.rust }}
          components: rustfmt, clippy

      - name: Build
        run: cargo build

      - name: Test
        run: cargo test

      - name: Fmt
        run: cargo fmt --all -- --check

      - name: Clippy
        run: cargo clippy --all-targets -- -D warnings

  docker-test:
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - uses: actions/checkout@v4
      - name: Test image build
        run: docker build .
